version: '3'
services:
  pokedexapp:
   
    build: 
      context: .
      dockerfile: Dockerfile
    image: pokedex-docker
    container_name: pokedexapp
    restart: always # reiniciar el contenedor si se detiene
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    # volumes:
    #   - ./:/var/www/pokedex
